deployment:
  tasks:
    - export DEPLOY_PATH=/home/roselong/public_html
    - cd /home/roselong/repositories/return-to-source
    - /usr/local/bin/yarn install
    - /usr/local/bin/yarn build
    - cp -R .next/* $DEPLOY_PATH/
